server:
  port: 9090
  tomcat:
    threads:
      max: 0
    uri-encoding: UTF-8
  reactive:
    session:
      timeout: 30

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_community?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB

#Mybatis:
#  mapper-localtions:
